"""created all tables

Revision ID: 6af57199340c
Revises: fb32bd014583
Create Date: 2026-04-10 17:33:01.237329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af57199340c'
down_revision = 'fb32bd014583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_owner_id'), ['owner_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_user_id'), ['user_id'], unique=False)

    op.create_table('room_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rp_user_id', sa.Integer(), nullable=False),
    sa.Column('rp_room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rp_room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['rp_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_participant_rp_room_id'), ['rp_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_participant_rp_user_id'), ['rp_user_id'], unique=False)

    op.create_table('transcript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_room_id'), ['room_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_room_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_created_at'))

    op.drop_table('transcript')
    with op.batch_alter_table('room_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_participant_rp_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_participant_rp_room_id'))

    op.drop_table('room_participant')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_room_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    op.drop_table('message')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_owner_id'))
        batch_op.drop_index(batch_op.f('ix_room_created_at'))

    op.drop_table('room')
    # ### end Alembic commands ###
