"""add room_code to room

Revision ID: 799b856699b5
Revises: 856c905d1755
Create Date: 2026-04-11 12:31:58.537131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799b856699b5'
down_revision = '856c905d1755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_code', sa.String(length=8), nullable=False))
        batch_op.create_index(batch_op.f('ix_room_room_code'), ['room_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_room_code'))
        batch_op.drop_column('room_code')

    # ### end Alembic commands ###
