"""new fields in user model

Revision ID: 856c905d1755
Revises: 6af57199340c
Create Date: 2026-04-10 20:03:12.304982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856c905d1755'
down_revision = '6af57199340c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
