"""fix room_code length and uniqueness

Revision ID: 8a2d4a8537eb
Revises: 799b856699b5
Create Date: 2026-04-11 12:54:22.926160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2d4a8537eb'
down_revision = '799b856699b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=9),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_room_room_code'))
        batch_op.create_index(batch_op.f('ix_room_room_code'), ['room_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_room_code'))
        batch_op.create_index(batch_op.f('ix_room_room_code'), ['room_code'], unique=False)
        batch_op.alter_column('room_code',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
